run smoke-tests

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -338,6 +338,7 @@ jobs:
           name: Send migration results to memstash
           command: |
             # Your code here
+            cd backend
             if grep -q "has been executed successfully" migration_data.txt
             then
               echo "Migrations success, updating memstash"
@@ -347,7 +348,7 @@ jobs:
               --data "1" \
               https://api.memstash.io/values/migrations_data
             else
-              echo "Migraitons failed"
+              echo "Migrations failed"
               curl -H "Content-Type: text/plain" \
               -H "token: ${CIRCLE_WORKFLOW_ID:0:7}" \
               --request PUT \
@@ -389,10 +390,10 @@ jobs:
           name: Deploy frontend objects
           command: |
             # your code here
+            npm install webpack-dev-server -g
             cd frontend
             npm install
-            npm install webpack-dev-server -g
-            npm install oauth-sign
+            # npm install oauth-sign
             npm run build
             aws s3 cp ./dist s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive
 
@@ -456,22 +457,29 @@ jobs:
             # your code here
             BACKEND_IP=$(curl -H "token: ${CIRCLE_WORKFLOW_ID:0:7}" --request GET https://api.memstash.io/values/url_backend_ip)
             echo ${BACKEND_IP}
-            export API_URL="https://${BACKEND_IP}:3030/api/status"
+            export API_URL="http://${BACKEND_IP}:3030/api/status"
+            echo ${API_URL}
       - run:
           name: Backend smoke test.
           command: |
             # your code here
-            curl -s $API_URL
+            # curl ${API_URL}
+            if curl -s ${API_URL} | grep "ok"
+            then
+              exit 0
+            else
+              exit 1
+            fi
       - run:
           name: Frontend smoke test.
           command: |
             # your code here
-            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-us-east-2.amazonaws.com/index.html#/employees"
+            URL="c"
             if curl -s ${URL} | grep "Welcome"
             then
-              return 0
+              exit 1
             else
-              return 1
+              exit 0
             fi
       # Here's where you will add some code to rollback on failure  
       - destroy-environment
@@ -544,8 +552,8 @@ workflows:
           requires: [run-migrations]
       - deploy-backend:
           requires: [run-migrations]
-      # - smoke-test:
-      #     requires: [deploy-backend, deploy-frontend]
+      - smoke-test:
+          requires: [deploy-backend, deploy-frontend]
       # - cloudfront-update:
       #     requires: [smoke-test]
       # - cleanup:
